### ISSUE TITLE
You should open discussions for this

### ISSUE THREAD

**Issue by rlewkowicz** [greatscottgadgets/facedancer#110]
I'd have to go look but some projects have "Q&A" and general convo. I ordered my cynthion and I'm so frigging excited it hurts. It was supposed to be here tuesday and I stare at the out for delivery as if it will make it come faster. 

I cannot wait to play with this. I'm incredibly excited and I'll want somewhere to talk about my explorations and share my findings

**Comment by martinling** [comment]
You might want to check out our [Discord](https://discord.gg/rsfMw3rsU8).
