### ISSUE TITLE
Questions on fuzzing and USB 2.0

### ISSUE THREAD

**Issue by tzewantp** [greatscottgadgets/facedancer#27]
Hi,
I am using a GreatFet One. 

(1) I would like to try out fuzzing with Facedancer. I am able to start facedancer-keyboard.py with the help of this link: https://github.com/usb-tools/Facedancer/issues/8. 

Using this same script, how should I begin to fuzz?  Are there any sample scripts or documented functions that I could use?

(2) Have another question which is similar to this post, https://github.com/usb-tools/Facedancer/issues/20. I would like to perform a proxy using a USB 2.0 mass storage device. At this moment, I got a "unable to enumerate USB device" error when I inserted a thumb drive. May I know will USB 2.0 mass storage devices be supported in Facedancer in the near future?

Thanks very much!

Regards,
Tzewan

**Comment by antoinevg** [comment]
Please check out the updated documentation: https://facedancer.readthedocs.io/en/latest/
