### ISSUE TITLE
facedancer-umass.py cannot mount in RW mode 

### ISSUE THREAD

**Issue by JimmyTD** [greatscottgadgets/Facedancer#65]
I have made a simple vfat32 disk image that i can separately mount and write to, however when i try to use it when on my greatfetOne using facedancer-umass.py it stops on the first write command in the sequence. It pauses at the performing WRITE command below in bold, before eventually trying to mount again i believe.  I have changed the mmap to prot=PROT_WRITE but this has not helped.  

I am using Ubuntu 20.04
thanks

<-- handling READ (IN) 512:[00 00 00 01 b1 00 00 01 00 00 00 00 00 00 00]
<-- performing READ (10), lba 433 + 1 block(s)
<-- reading sector 433 [all zeroes]
--> responded with 512 bytes
<-- handling READ (IN) 512:[00 00 00 01 b2 00 00 01 00 00 00 00 00 00 00]
<-- performing READ (10), lba 434 + 1 block(s)
<-- reading sector 434 [all zeroes]
--> responded with 512 bytes
<-- handling READ (IN) 512:[00 00 00 01 b3 00 00 01 00 00 00 00 00 00 00]
<-- performing READ (10), lba 435 + 1 block(s)
<-- reading sector 435 [all zeroes]
--> responded with 512 bytes
--> handling WRITE (10) (OUT) 512:[00 00 00 00 00 00 00 01 00 00 00 00 00 00 00]
**--> performing WRITE (10), lba 0 + 1 block**(**s)
USB mass storage device received request <, standard request to device (GET_DESCRIPTOR: value=DEVICE descriptor (index=0x00), index=0, length=64)
USB mass storage device received GET_DESCRIPTOR req 1, index 0, language 0x0000, length 64
USB mass storage device received request <, standard request to device (GET_DESCRIPTOR: value=DEVICE descriptor (index=0x00), index=0, length=18)
USB mass storage device received GET_DESCRIPTOR req 1, index 0, language 0x0000, length 18
USB mass storage device received request <, standard request to device (GET_DESCRIPTOR: value=CONFIGURATION descriptor (index=0x00), index=0, length=32)
USB mass storage device received GET_DESCRIPTOR req 2, index 0, language 0x0000, length 32
USB mass storage device received request <, standard request to device (GET_DESCRIPTOR: value=STRING descriptor (index=0x03), index=409, length=255)
USB mass storage device received GET_DESCRIPTOR req 3, index 3, language 0x0409, length 255
USB mass storage device received request >, standard request to device (SET_CONFIGURATION: value=1, index=0, length=0)
USB mass storage device received SET_CONFIGURATION request
--> continue write with 31 more bytes of data

**Comment by shutingrz** [comment]
The following issue may be helpful.

https://github.com/greatscottgadgets/greatfet/issues/373#issuecomment-1207495173

**Comment by antoinevg** [comment]
Fixed in: https://github.com/greatscottgadgets/greatfet/pull/425
